### PR TITLE
[sys<-BE] Server Deployment

### PR DESCRIPTION
**Pull request by pjhcsols**
프로젝트 환경 정보 (web3-credential-server)

OS 및 IDE:
•	OS: macOS
•	IDE: IntelliJ IDEA
•	Framework: Spring Boot 3.3.1
•	Java: Java 21
•	Bean ID: 4eb0ed44
 
환경변수 설정:
1.	Spring 설정:
o	spring.application.name: spring-gift-test
o	spring.datasource.url: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1
o	spring.jpa.hibernate.ddl-auto: create
o	spring.h2.console.enabled: true
o	spring.main.allow-bean-definition-overriding: true
2.	AWS S3 설정:
o	cloud.aws.s3BucketName: (실제값 필요)
o	cloud.aws.s3BucketUrl: (실제값 필요)
o	cloud.aws.credentialsAccessKey: (실제값 필요)
o	cloud.aws.credentialsSecretKey: (실제값 필요)
o	cloud.aws.region-static: ap-northeast-2
o	cloud.aws.stack.auto: false
3.	JWT 설정:
o	jwt.key: (실제값 필요)
o	jwt.access-token-validity: 3600000 (1시간)
4.	Kakao 설정:
o	kakao.client-id: (appkey 사용)
o	kakao.redirect-uri: http://localhost:8080
 
Docker 및 Hyperledger 환경:
1.	Docker 환경:
o	Client Version: 24.0.5
o	API Version: 1.43
o	Go Version: go1.20.6
o	OS/Arch: darwin/arm64
o	Context: desktop-linux
2.	Docker Desktop:
o	Version: 4.22.1 (118664)
o	Engine: 24.0.5
o	Containerd Version: 1.6.21
o	Runc Version: 1.1.7
o	Docker-init Version: 0.19.0
 
Hyperledger Fabric 설정:
•	Peer Version: v3.0.0
•	Go Version: go1.23.1
•	Architecture: linux/arm64
•	License: Apache License 2.0

### CODE REVIEW

**Comment by seakim-knu** [comment]
confirm 이요

**Review by seakim-knu — APPROVED** [review]
confirm 이요~~~

**Review by KimGona — APPROVED** [review]
confirm

**Review by jinno321 — APPROVED** [review]
confirm

**Comment by pjhcsols** [comment]
confirm

**Pull request merged**
